version: "3.4"
services:
  postgres:
    build:
      context: ".."
      dockerfile: "containers/postgres/Dockerfile"
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    hostname: postgres
    networks:
      - staging
    ports:
      - ${PSQL_PORT}:${PSQL_PORT}
    expose:
      - ${PSQL_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - dumps:/dumps
    command: -p ${PSQL_PORT} # postgres -c max_wal_size=3GB
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p ${PSQL_PORT} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: -p ${PSQL_PORT}





volumes:
  pg_data:
  dumps:

networks:
  staging:
      driver: bridge